#!/bin/bash
_LOG_FPATH="/src/.logs/hugo-asciidoctor.log"
_DATE_TIME=$(TZ=UTC-9 date "+%Y/%m/%d %H:%M:%S.%N")
_CONTAINER_NAME="${HADV_NAME_PREFIX}-hadv-asciidoctor"
if [ ! -d "${_LOG_FPATH%/*}" ]; then mkdir -p "${_LOG_FPATH%/*}"; fi
echo "${_DATE_TIME} - [Asciidoctor] ${_CONTAINER_NAME}: $@" >> "${_LOG_FPATH}"
docker exec -i "${_CONTAINER_NAME}" asciidoctor "$@"
